---
language: ruby
script: bundle exec rspec
rvm:
- 1.9.3
services:
- redis-server
notifications:
  email: false
  campfire:
    rooms:
    - secure: ! 'OuZ21jd2xpXCL61aCPcKmvN8ugQyRPLJmfuwMgYmlm4bJR3FYZPA6lALROhU

        KAfVw0whAb5G+ojC7l0B6t2mA9YbDdg19+m1vzUF03E+5nMSYXvV6wl8Gcb6

        rFpdHc9oVdNe0GucqDHB8YQjw+ToXjvJlz07qyFf3KIAW2bPayA='
